export default function Home() {
    return (
        <main className="min-h-screen bg-white">
              {/* Header */}
                    <nav className="bg-blue-900 p-4">
                            <h1 className="text-white text-xl font-bold">
                                      Vertex ResearchSuite
                                              </h1>
                                                      <p className="text-blue-200 text-sm">
                                                                by Talabi Vertex Group
                                                                        </p>
                                                                              </nav>

                                                                                    {/* Hero Section */}
                                                                                          <div className="bg-blue-900 text-white py-16 px-6 text-center">
                                                                                                  <h2 className="text-3xl font-bold mb-4">
                                                                                                            Nigeria's #1 Academic Research Assistant
                                                                                                                    </h2>
                                                                                                                            <p className="text-lg text-blue-200 mb-8">
                                                                                                                                      Generate professional research topics and 
                                                                                                                                                full proposals tailored specifically for 
                                                                                                                                                          Nigerian universities, polytechnics and 
                                                                                                                                                                    colleges of education.
                                                                                                                                                                            </p>
                                                                                                                                                                                    <div className="flex flex-col gap-4 max-w-xs mx-auto">
                                                                                                                                                                                              <a href="/signup" className="bg-white text-blue-900 
                                                                                                                                                                                                          font-bold py-3 px-6 rounded-lg text-center">
                                                                                                                                                                                                                      Get Started Free
                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                          <a href="/login" className="border border-white 
                                                                                                                                                                                                                                                      text-white font-bold py-3 px-6 rounded-lg text-center">
                                                                                                                                                                                                                                                                  Login
                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                {/* Features */}
                                                                                                                                                                                                                                                                                                      <div className="py-12 px-6">
                                                                                                                                                                                                                                                                                                              <h3 className="text-2xl font-bold text-center 
                                                                                                                                                                                                                                                                                                                        text-blue-900 mb-8">
                                                                                                                                                                                                                                                                                                                                  What We Offer
                                                                                                                                                                                                                                                                                                                                          </h3>
                                                                                                                                                                                                                                                                                                                                                  <div className="flex flex-col gap-6 max-w-lg mx-auto">
                                                                                                                                                                                                                                                                                                                                                            <div className="border border-blue-100 
                                                                                                                                                                                                                                                                                                                                                                        rounded-lg p-6 shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                                    <h4 className="font-bold text-blue-900 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                  📚 Research Topic Generator
                                                                                                                                                                                                                                                                                                                                                                                                              </h4>
                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                        Get 5 unique research topics tailored to 
                                                                                                                                                                                                                                                                                                                                                                                                                                                      your institution and course of study.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="border border-blue-100 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  rounded-lg p-6 shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h4 className="font-bold text-blue-900 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            📝 Full Proposal Generator
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Receive 5 complete research proposals 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                in proper Nigerian academic format.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="border border-blue-100 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            rounded-lg p-6 shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h4 className="font-bold text-blue-900 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      📊 Data Analysis
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Analyze your research data and get 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          detailed academic reports instantly.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Footer */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <footer className="bg-blue-900 text-white 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  text-center py-6 px-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="font-bold">Vertex ResearchSuite</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-blue-200 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Building Nigeria, For The World
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-blue-300 text-xs mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      © 2026 Talabi Vertex Group of Companies
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } 
}